spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/userservice?serverTimezone=UTC'
    password: 'root'
    username: 'root'
  jpa:
    hibernate:
      # ddl-auto: 'none'
      ddl-auto: 'update'
      open-in-view: 'false'
      show-sql: 'false'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
        format_sql: 'true'
        jdbc:
          time_zone: 'UTC'
server:
  port: 8082
logger:
  org:
    hibernate:
      dialect:
        function:
          TemplateRenderer:
            level: 'ERR'
